import type { Meta, StoryObj } from "@storybook/react";
import { Input } from "./Input";

const meta: Meta<typeof Input> = {
  title: "UI/Input",
  component: Input,
  tags: ["autodocs"],
  argTypes: {
    label: {
      control: "text",
      description: "Label above the input",
    },
    placeholder: {
      control: "text",
      description: "Placeholder text inside the input",
    },
    error: {
      control: "text",
      description: "Error message indicating invalid state",
    },
    helperText: {
      control: "text",
      description: "Helpful text below the input",
    },
    disabled: {
      control: "boolean",
      description: "Disables the input field",
    },
    required: {
      control: "boolean",
      description: "Whether the input is required",
    },
  },
};

export default meta;
type Story = StoryObj<typeof Input>;

export const Default: Story = {
  args: {
    label: "Email Address",
    placeholder: "you@example.com",
    helperText: "We'll never share your email with anyone.",
  },
};

export const WithError: Story = {
  args: {
    label: "Amount (NGN)",
    defaultValue: "-500",
    error: "Please enter a valid amount of at least ₦100.",
  },
};

export const Disabled: Story = {
  args: {
    label: "Wallet Address",
    value: "CCBJ235OCBFZXBFSUUUT4PMG7RRCAXZXMUEB2L7CTTQ5NRSNO4P2SLNP",
    disabled: true,
    helperText: "Generated by Soroban escrow contract.",
  },
};
