import "./env";
import { setupServer } from "msw/node";
import { http, HttpResponse } from "msw";

/**
 * mockHttp.ts — msw request interceptors for ALL outbound HTTP calls.
 *
 * No integration test ever touches the real internet. The default handlers
 * below emulate:
 *   - Termii   (OTP send / verify)
 *   - Paystack (bank list / account resolution)
 *   - Stellar  (Friendbot funding + Horizon account/balance lookups)
 *
 * `onUnhandledRequest: "error"` makes the suite fail loudly if any code path
 * attempts an un-mocked external call.
 *
 * Individual tests override handlers with `server.use(...)` for error and
 * edge cases; `server.resetHandlers()` restores defaults after every test.
 */

export const TERMII_SEND_URL = "https://api.ng.termii.com/api/sms/otp/send";
export const TERMII_VERIFY_URL = "https://api.ng.termii.com/api/sms/otp/verify";
export const PAYSTACK_BANKS_URL = "https://api.paystack.co/bank";
export const PAYSTACK_RESOLVE_URL = "https://api.paystack.co/bank/resolve";
export const FRIENDBOT_URL = "https://friendbot.stellar.org*";
export const HORIZON_ACCOUNT_URL = "https://horizon-testnet.stellar.org/accounts/:publicKey";

/** Captures the last Termii send payload so tests can assert on it. */
export const captured = {
  termiiSend: null as Record<string, unknown> | null,
  termiiVerify: null as Record<string, unknown> | null,
};

export const defaultHandlers = [
  // -- Termii ---------------------------------------------------------------
  http.post(TERMII_SEND_URL, async ({ request }) => {
    captured.termiiSend = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json({ pinId: "test-pin-id-123", status: "success" });
  }),

  http.post(TERMII_VERIFY_URL, async ({ request }) => {
    captured.termiiVerify = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json({ verified: true, msisdn: "+2348012345678" });
  }),

  // -- Paystack ---------------------------------------------------------------
  http.get(PAYSTACK_BANKS_URL, () =>
    HttpResponse.json({
      status: true,
      message: "Banks retrieved",
      data: [
        { name: "Access Bank", code: "044", active: true },
        { name: "Guaranty Trust Bank", code: "058", active: true },
      ],
    })
  ),

  http.get(PAYSTACK_RESOLVE_URL, () =>
    HttpResponse.json({
      status: true,
      data: { account_number: "0123456789", account_name: "JANE DOE" },
    })
  ),

  // -- Stellar ---------------------------------------------------------------
  // Friendbot funds a freshly generated keypair.
  http.get(FRIENDBOT_URL, () => HttpResponse.json({ ok: true })),

  // Horizon account lookup — minimal shape parsed by @stellar/stellar-sdk's
  // Horizon.Server#loadAccount (needs account_id, sequence, balances).
  http.get(HORIZON_ACCOUNT_URL, ({ params }) =>
    HttpResponse.json(horizonAccount(params["publicKey"] as string, "10000.0000000"))
  ),
];

/** Builds a minimal but SDK-parseable Horizon account response. */
export function horizonAccount(publicKey: string, xlmBalance: string) {
  return {
    _links: {
      self: { href: `https://horizon-testnet.stellar.org/accounts/${publicKey}` },
      transactions: { href: `https://horizon-testnet.stellar.org/accounts/${publicKey}/transactions{?cursor,limit,order}`, templated: true },
      operations: { href: `https://horizon-testnet.stellar.org/accounts/${publicKey}/operations{?cursor,limit,order}`, templated: true },
      payments: { href: `https://horizon-testnet.stellar.org/accounts/${publicKey}/payments{?cursor,limit,order}`, templated: true },
    },
    id: publicKey,
    account_id: publicKey,
    sequence: "1000000000000000",
    subentry_count: 0,
    thresholds: { low_threshold: 0, med_threshold: 0, high_threshold: 0 },
    flags: { auth_required: false, auth_revocable: false, auth_immutable: false, auth_clawback_enabled: false },
    signers: [{ weight: 1, key: publicKey, type: "ed25519_public_key", sponsor: false }],
    data: {},
    balances: [
      {
        balance: xlmBalance,
        buying_liabilities: "0.0000000",
        selling_liabilities: "0.0000000",
        asset_type: "native",
        last_modified_ledger: 1,
        sponsor: null,
      },
    ],
    paging_token: publicKey,
  };
}

export const server = setupServer(...defaultHandlers);

/** Registers msw lifecycle hooks for a test file. */
export function setupMsw(): void {
  beforeAll(() =>
    server.listen({
      // Fail loudly on any un-mocked EXTERNAL call, while letting the
      // loopback traffic generated by supertest/the app itself through.
      onUnhandledRequest: (request) => {
        const { hostname } = new URL(request.url);
        if (hostname === "127.0.0.1" || hostname === "localhost") return;
        throw new Error(
          `[test] Unhandled external HTTP request: ${request.method} ${request.url}`
        );
      },
    })
  );
  afterEach(() => {
    server.resetHandlers();
    captured.termiiSend = null;
    captured.termiiVerify = null;
  });
  afterAll(() => server.close());
}
