import type { MetadataRoute } from "next";

import { PRIVATE_ROUTES, siteUrl } from "./lib/seo";

/**
 * robots.txt, generated by Next.js (Issue #28).
 *
 * Private areas are disallowed here *and* carry `robots: { index: false }` in
 * their own metadata. Both are needed: robots.txt asks a crawler not to fetch
 * the page, while the meta directive is what keeps it out of an index if it
 * reaches the URL another way — a shared link, a backlink, or a crawler that
 * ignores the file.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: PRIVATE_ROUTES.map((route) => `${route}/`),
    },
    sitemap: `${siteUrl()}/sitemap.xml`,
  };
}
