import type { MetadataRoute } from "next";

import { PUBLIC_ROUTES, siteUrl } from "./lib/seo";

/**
 * sitemap.xml, generated by Next.js (Issue #28).
 *
 * Lists only public, stable routes. Wallet, profile, auth and admin are
 * deliberately absent — they are private to a signed-in user, so pointing a
 * crawler at them wastes its budget and surfaces nothing useful.
 *
 * Individual trades are not enumerated either: they expire, and a sitemap full
 * of dead listings trains a crawler to distrust the file.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const base = siteUrl();
  const lastModified = new Date();

  return PUBLIC_ROUTES.map((route) => ({
    url: `${base}${route.path}`,
    lastModified,
    changeFrequency: route.changeFrequency,
    priority: route.priority,
  }));
}
