import type { MetadataRoute } from "next";

import type { TradeOffer } from "../../server/src/types/trade";
import { PUBLIC_ROUTES, siteUrl } from "./lib/seo";

/**
 * sitemap.xml, generated by Next.js (Issue #28, Issue #381).
 *
 * Lists the public, stable routes plus the currently *active* trade listings
 * (`/trades/<id>`). Wallet, profile, auth and admin stay out — they are private
 * to a signed-in user, so pointing a crawler at them wastes its budget and
 * surfaces nothing useful.
 *
 * Only `Active` trades are enumerated (they are the ones a crawler can still
 * reach); each entry carries the trade's `updated_at` as `lastModified`. The
 * list is refreshed by ISR every 15 minutes.
 */

/** Regenerate (ISR) at most every 15 minutes. */
export const revalidate = 900;

/** Trades requested per page from the public listing API. */
const TRADES_PAGE_SIZE = 100;
/** Safety cap so a runaway backlog can never produce an unbounded sitemap. */
const TRADES_MAX_PAGES = 5;

interface TradesResponse {
  data?: TradeOffer[];
  pagination?: {
    page?: number;
    totalPages?: number;
  };
}

function apiBaseUrl(): string {
  return process.env["NEXT_PUBLIC_API_URL"] ?? "http://localhost:3001";
}

/**
 * Fetch the active trade listings to advertise in the sitemap.
 *
 * Best-effort: a flaky or unavailable API must never break the build or the
 * sitemap, so failures degrade to the static routes only.
 */
async function fetchActiveTrades(): Promise<TradeOffer[]> {
  const base = apiBaseUrl();
  const trades: TradeOffer[] = [];

  try {
    for (let page = 1; page <= TRADES_MAX_PAGES; page += 1) {
      const response = await fetch(
        `${base}/api/v1/trades?page=${page}&limit=${TRADES_PAGE_SIZE}`,
        { next: { revalidate } },
      );
      if (!response.ok) break;

      const body = (await response.json()) as TradesResponse;
      const batch = (body.data ?? []).filter((trade) => trade.status === "Active");
      trades.push(...batch);

      const totalPages = body.pagination?.totalPages ?? page;
      if (page >= totalPages || (body.data ?? []).length === 0) break;
    }
  } catch {
    return [];
  }

  return trades;
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const base = siteUrl();
  const lastModified = new Date();

  const staticEntries: MetadataRoute.Sitemap = PUBLIC_ROUTES.map((route) => ({
    url: `${base}${route.path}`,
    lastModified,
    changeFrequency: route.changeFrequency,
    priority: route.priority,
  }));

  const trades = await fetchActiveTrades();
  const tradeEntries: MetadataRoute.Sitemap = trades.map((trade) => ({
    url: `${base}/trades/${trade.id}`,
    lastModified: trade.updated_at ? new Date(trade.updated_at) : lastModified,
    changeFrequency: "daily",
    priority: 0.6,
  }));

  return [...staticEntries, ...tradeEntries];
}
